### PR TITLE
Fix Webidl respec errors

### LINKED ISSUE #212: WebIDL errors
Some interfaces defined in the original specification were never implemented, and the definitions of them are now flagged by ReSpec,  As such, they can be fixed through removal.  There may be other un-flagged errors especially in the WebIDL interfaces, which have not been properly maintained, I would say. 

cc @erictheise

### PR DESCRIPTION
**Pull request by prushforth**
Closes #212

### CODE REVIEW

**Review by Malvoz — COMMENTED** [review]
I believe we'll want to remove:

https://github.com/Maps4HTML/MapML/blob/9368ab7a95807bf64525941c695e95c12ea866ae/spec/index.html#L1886-L1891

There's also mention of legends in:
https://github.com/Maps4HTML/MapML/blob/9368ab7a95807bf64525941c695e95c12ea866ae/spec/index.html#L3341

**Comment by prushforth** [comment]
> I believe we'll want to remove:
> 
> https://github.com/Maps4HTML/MapML/blob/9368ab7a95807bf64525941c695e95c12ea866ae/spec/index.html#L1886-L1891
> 

I don't believe so, but there's certainly more work that we should do in improving how to define and link to, display and interact with legends.

Specifically, the `legend` link relation is used in the 

`<link rel="legend" href="https://cwfis.cfs.nrcan.gc.ca/geoserver/public/ows?service=WMS&request=GetLegendGraphic&format=image/png&width=20&height=20&layer=fdr_current"/>`

construct, which is used to create an `<a href="...">Layer label</a>` in the layer control: 
image

which was about the best I could do with the legend abstraction at the time, working as I was with the WMS specification.

> There's also mention of legends in:
> https://github.com/Maps4HTML/MapML/blob/9368ab7a95807bf64525941c695e95c12ea866ae/spec/index.html#L3341

I'm no longer convinced that legends are fully out of scope, since legend information could be important for map accessibility.  I wrote that, I think I did, at least, while thinking about the relationship of maps to HTML documents at large, and not wanting to introduce more abstractions into this proposal than strictly necessary ("legend" being an abstraction).  Do you think I should delete or amend the example of what's out of scope?  That paragraph relates to non-interactive user agents such as printers, but of course legends play an important role in printed maps as well.

**Comment by Malvoz** [comment]
Okay, while I think legends being links (`rel="legend"`) is somewhat problematic as described in https://github.com/Maps4HTML/MapML/issues/80#issuecomment-770051938 we can leave them as such for now.

**Review by Malvoz — APPROVED** [review]
There's a merge conflict, other than that LGTM!

**Pull request merged**
